//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogiFlow.Mobile.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogiFlow.Mobile.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid username or password..
        /// </summary>
        internal static string ErrorInvalidCredentials {
            get {
                return ResourceManager.GetString("ErrorInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid server URL. Please enter a valid http or https address..
        /// </summary>
        internal static string ErrorInvalidUrl {
            get {
                return ResourceManager.GetString("ErrorInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scanner test failed. Please check the device and try again..
        /// </summary>
        internal static string ErrorScannerTestFailed {
            get {
                return ResourceManager.GetString("ErrorScannerTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timeout must be greater than 0..
        /// </summary>
        internal static string ErrorTimeoutInvalid {
            get {
                return ResourceManager.GetString("ErrorTimeoutInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred. Please try again..
        /// </summary>
        internal static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred during authentication. Please try again..
        /// </summary>
        internal static string ErrorUnexpectedAuth {
            get {
                return ResourceManager.GetString("ErrorUnexpectedAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string LoginPasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string LoginUsernamePlaceholder {
            get {
                return ResourceManager.GetString("LoginUsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventory.
        /// </summary>
        internal static string MenuInventory {
            get {
                return ResourceManager.GetString("MenuInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item Info.
        /// </summary>
        internal static string MenuItemInfo {
            get {
                return ResourceManager.GetString("MenuItemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        internal static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movements.
        /// </summary>
        internal static string MenuMovements {
            get {
                return ResourceManager.GetString("MenuMovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Picking.
        /// </summary>
        internal static string MenuPicking {
            get {
                return ResourceManager.GetString("MenuPicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reception.
        /// </summary>
        internal static string MenuReception {
            get {
                return ResourceManager.GetString("MenuReception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main Menu.
        /// </summary>
        internal static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to server. Please check the URL and try again..
        /// </summary>
        internal static string Msg_TestErrorConnection {
            get {
                return ResourceManager.GetString("Msg_TestErrorConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active user.
        /// </summary>
        internal static string SettingsActiveUser {
            get {
                return ResourceManager.GetString("SettingsActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Demo mode.
        /// </summary>
        internal static string SettingsDemoMode {
            get {
                return ResourceManager.GetString("SettingsDemoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Environment.
        /// </summary>
        internal static string SettingsEnvironment {
            get {
                return ResourceManager.GetString("SettingsEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error sound.
        /// </summary>
        internal static string SettingsErrorSound {
            get {
                return ResourceManager.GetString("SettingsErrorSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        internal static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore defaults.
        /// </summary>
        internal static string SettingsRestoreDefaults {
            get {
                return ResourceManager.GetString("SettingsRestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scanner type.
        /// </summary>
        internal static string SettingsScannerType {
            get {
                return ResourceManager.GetString("SettingsScannerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string SettingsSectionAbout {
            get {
                return ResourceManager.GetString("SettingsSectionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        internal static string SettingsSectionGeneral {
            get {
                return ResourceManager.GetString("SettingsSectionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scanner.
        /// </summary>
        internal static string SettingsSectionScanner {
            get {
                return ResourceManager.GetString("SettingsSectionScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server / Environment.
        /// </summary>
        internal static string SettingsSectionServer {
            get {
                return ResourceManager.GetString("SettingsSectionServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server URL.
        /// </summary>
        internal static string SettingsServerUrl {
            get {
                return ResourceManager.GetString("SettingsServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success sound.
        /// </summary>
        internal static string SettingsSuccessSound {
            get {
                return ResourceManager.GetString("SettingsSuccessSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success vibration.
        /// </summary>
        internal static string SettingsSuccessVibration {
            get {
                return ResourceManager.GetString("SettingsSuccessVibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test connection.
        /// </summary>
        internal static string SettingsTestConnection {
            get {
                return ResourceManager.GetString("SettingsTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test scanner.
        /// </summary>
        internal static string SettingsTestScanner {
            get {
                return ResourceManager.GetString("SettingsTestScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visual theme.
        /// </summary>
        internal static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timeout (sec).
        /// </summary>
        internal static string SettingsTimeout {
            get {
                return ResourceManager.GetString("SettingsTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string SettingsUser {
            get {
                return ResourceManager.GetString("SettingsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        internal static string SettingsVersion {
            get {
                return ResourceManager.GetString("SettingsVersion", resourceCulture);
            }
        }
    }
}
