//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogiFlow.Mobile.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogiFlow.Mobile.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 💬 Ask AI.
        /// </summary>
        internal static string AiChatAskButton {
            get {
                return ResourceManager.GetString("AiChatAskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        internal static string AiChatClear {
            get {
                return ResourceManager.GetString("AiChatClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, I couldn&apos;t reach the AI service. Please try again..
        /// </summary>
        internal static string AiChatErrorService {
            get {
                return ResourceManager.GetString("AiChatErrorService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hi! I&apos;m your LogiFlow assistant. I can help you with {0}. What do you need?.
        /// </summary>
        internal static string AiChatGreeting {
            get {
                return ResourceManager.GetString("AiChatGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type your question….
        /// </summary>
        internal static string AiChatPlaceholder {
            get {
                return ResourceManager.GetString("AiChatPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assistant is thinking….
        /// </summary>
        internal static string AiChatThinking {
            get {
                return ResourceManager.GetString("AiChatThinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AI Assistant.
        /// </summary>
        internal static string AiChatTitle {
            get {
                return ResourceManager.GetString("AiChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel scan.
        /// </summary>
        internal static string CameraScanCancel {
            get {
                return ResourceManager.GetString("CameraScanCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Point the camera at the barcode.
        /// </summary>
        internal static string CameraScanInstruction {
            get {
                return ResourceManager.GetString("CameraScanInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scan Barcode.
        /// </summary>
        internal static string CameraScanTitle {
            get {
                return ResourceManager.GetString("CameraScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string CommonBack {
            get {
                return ResourceManager.GetString("CommonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string CommonCancel {
            get {
                return ResourceManager.GetString("CommonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Demo.
        /// </summary>
        internal static string EnvironmentDemo {
            get {
                return ResourceManager.GetString("EnvironmentDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Production.
        /// </summary>
        internal static string EnvironmentProduction {
            get {
                return ResourceManager.GetString("EnvironmentProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid username or password..
        /// </summary>
        internal static string ErrorInvalidCredentials {
            get {
                return ResourceManager.GetString("ErrorInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid server URL. Please enter a valid http or https address..
        /// </summary>
        internal static string ErrorInvalidUrl {
            get {
                return ResourceManager.GetString("ErrorInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scanner test failed. Please check the device and try again..
        /// </summary>
        internal static string ErrorScannerTestFailed {
            get {
                return ResourceManager.GetString("ErrorScannerTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timeout must be greater than 0..
        /// </summary>
        internal static string ErrorTimeoutInvalid {
            get {
                return ResourceManager.GetString("ErrorTimeoutInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred. Please try again..
        /// </summary>
        internal static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred during authentication. Please try again..
        /// </summary>
        internal static string ErrorUnexpectedAuth {
            get {
                return ResourceManager.GetString("ErrorUnexpectedAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string LoginPasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string LoginUsernamePlaceholder {
            get {
                return ResourceManager.GetString("LoginUsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventory.
        /// </summary>
        internal static string MenuInventory {
            get {
                return ResourceManager.GetString("MenuInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item Info.
        /// </summary>
        internal static string MenuItemInfo {
            get {
                return ResourceManager.GetString("MenuItemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        internal static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movements.
        /// </summary>
        internal static string MenuMovements {
            get {
                return ResourceManager.GetString("MenuMovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Picking.
        /// </summary>
        internal static string MenuPicking {
            get {
                return ResourceManager.GetString("MenuPicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reception.
        /// </summary>
        internal static string MenuReception {
            get {
                return ResourceManager.GetString("MenuReception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main Menu.
        /// </summary>
        internal static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to server. Please check the URL and try again..
        /// </summary>
        internal static string Msg_TestErrorConnection {
            get {
                return ResourceManager.GetString("Msg_TestErrorConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transport label is readable.
        /// </summary>
        internal static string ReceptionCheckLabelReadable {
            get {
                return ResourceManager.GetString("ReceptionCheckLabelReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All checks completed.
        /// </summary>
        internal static string ReceptionChecklistComplete {
            get {
                return ResourceManager.GetString("ReceptionChecklistComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        internal static string ReceptionChecklistContinue {
            get {
                return ResourceManager.GetString("ReceptionChecklistContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complete all checks before continuing.
        /// </summary>
        internal static string ReceptionChecklistInstruction {
            get {
                return ResourceManager.GetString("ReceptionChecklistInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending checks.
        /// </summary>
        internal static string ReceptionChecklistPending {
            get {
                return ResourceManager.GetString("ReceptionChecklistPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification checklist.
        /// </summary>
        internal static string ReceptionChecklistSectionTitle {
            get {
                return ResourceManager.GetString("ReceptionChecklistSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Checklist.
        /// </summary>
        internal static string ReceptionChecklistTitle {
            get {
                return ResourceManager.GetString("ReceptionChecklistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Packaging is in good condition.
        /// </summary>
        internal static string ReceptionCheckPackagingOk {
            get {
                return ResourceManager.GetString("ReceptionCheckPackagingOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity matches delivery note.
        /// </summary>
        internal static string ReceptionCheckQuantityVerified {
            get {
                return ResourceManager.GetString("ReceptionCheckQuantityVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sample is intact and undamaged.
        /// </summary>
        internal static string ReceptionCheckSampleIntact {
            get {
                return ResourceManager.GetString("ReceptionCheckSampleIntact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sample is correctly labeled.
        /// </summary>
        internal static string ReceptionCheckSampleLabeled {
            get {
                return ResourceManager.GetString("ReceptionCheckSampleLabeled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temperature conditions verified.
        /// </summary>
        internal static string ReceptionCheckTemperatureOk {
            get {
                return ResourceManager.GetString("ReceptionCheckTemperatureOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle condition is acceptable.
        /// </summary>
        internal static string ReceptionCheckVehicleCondition {
            get {
                return ResourceManager.GetString("ReceptionCheckVehicleCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle documentation is complete.
        /// </summary>
        internal static string ReceptionCheckVehicleDocumentation {
            get {
                return ResourceManager.GetString("ReceptionCheckVehicleDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        internal static string ReceptionConfirmationConfirm {
            get {
                return ResourceManager.GetString("ReceptionConfirmationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flow type.
        /// </summary>
        internal static string ReceptionConfirmationFlowType {
            get {
                return ResourceManager.GetString("ReceptionConfirmationFlowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reception number.
        /// </summary>
        internal static string ReceptionConfirmationNumber {
            get {
                return ResourceManager.GetString("ReceptionConfirmationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recipient.
        /// </summary>
        internal static string ReceptionConfirmationRecipient {
            get {
                return ResourceManager.GetString("ReceptionConfirmationRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject.
        /// </summary>
        internal static string ReceptionConfirmationReject {
            get {
                return ResourceManager.GetString("ReceptionConfirmationReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm rejection.
        /// </summary>
        internal static string ReceptionConfirmationRejectConfirm {
            get {
                return ResourceManager.GetString("ReceptionConfirmationRejectConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter rejection reason.
        /// </summary>
        internal static string ReceptionConfirmationRejectionPlaceholder {
            get {
                return ResourceManager.GetString("ReceptionConfirmationRejectionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rejection reason.
        /// </summary>
        internal static string ReceptionConfirmationRejectionReason {
            get {
                return ResourceManager.GetString("ReceptionConfirmationRejectionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rejection reason.
        /// </summary>
        internal static string ReceptionConfirmationSectionRejection {
            get {
                return ResourceManager.GetString("ReceptionConfirmationSectionRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reception summary.
        /// </summary>
        internal static string ReceptionConfirmationSectionSummary {
            get {
                return ResourceManager.GetString("ReceptionConfirmationSectionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sender.
        /// </summary>
        internal static string ReceptionConfirmationSender {
            get {
                return ResourceManager.GetString("ReceptionConfirmationSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation.
        /// </summary>
        internal static string ReceptionConfirmationTitle {
            get {
                return ResourceManager.GetString("ReceptionConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total lines.
        /// </summary>
        internal static string ReceptionConfirmationTotalLines {
            get {
                return ResourceManager.GetString("ReceptionConfirmationTotalLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total quantity.
        /// </summary>
        internal static string ReceptionConfirmationTotalQuantity {
            get {
                return ResourceManager.GetString("ReceptionConfirmationTotalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add line.
        /// </summary>
        internal static string ReceptionDetailAddLine {
            get {
                return ResourceManager.GetString("ReceptionDetailAddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Article.
        /// </summary>
        internal static string ReceptionDetailArticle {
            get {
                return ResourceManager.GetString("ReceptionDetailArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scan or enter article code.
        /// </summary>
        internal static string ReceptionDetailArticlePlaceholder {
            get {
                return ResourceManager.GetString("ReceptionDetailArticlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        internal static string ReceptionDetailContinue {
            get {
                return ResourceManager.GetString("ReceptionDetailContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depth.
        /// </summary>
        internal static string ReceptionDetailDepth {
            get {
                return ResourceManager.GetString("ReceptionDetailDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observations.
        /// </summary>
        internal static string ReceptionDetailExtraObservations {
            get {
                return ResourceManager.GetString("ReceptionDetailExtraObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Height.
        /// </summary>
        internal static string ReceptionDetailHeight {
            get {
                return ResourceManager.GetString("ReceptionDetailHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location.
        /// </summary>
        internal static string ReceptionDetailLocation {
            get {
                return ResourceManager.GetString("ReceptionDetailLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scan or enter location code.
        /// </summary>
        internal static string ReceptionDetailLocationPlaceholder {
            get {
                return ResourceManager.GetString("ReceptionDetailLocationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lot number.
        /// </summary>
        internal static string ReceptionDetailLotNumber {
            get {
                return ResourceManager.GetString("ReceptionDetailLotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter lot number.
        /// </summary>
        internal static string ReceptionDetailLotNumberPlaceholder {
            get {
                return ResourceManager.GetString("ReceptionDetailLotNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No detail lines added yet.
        /// </summary>
        internal static string ReceptionDetailNoLines {
            get {
                return ResourceManager.GetString("ReceptionDetailNoLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity.
        /// </summary>
        internal static string ReceptionDetailQuantity {
            get {
                return ResourceManager.GetString("ReceptionDetailQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter quantity.
        /// </summary>
        internal static string ReceptionDetailQuantityPlaceholder {
            get {
                return ResourceManager.GetString("ReceptionDetailQuantityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sample reference.
        /// </summary>
        internal static string ReceptionDetailSampleReference {
            get {
                return ResourceManager.GetString("ReceptionDetailSampleReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scan or enter sample reference.
        /// </summary>
        internal static string ReceptionDetailSampleReferencePlaceholder {
            get {
                return ResourceManager.GetString("ReceptionDetailSampleReferencePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dimensions / Weight.
        /// </summary>
        internal static string ReceptionDetailSectionDimensions {
            get {
                return ResourceManager.GetString("ReceptionDetailSectionDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detail lines.
        /// </summary>
        internal static string ReceptionDetailSectionLines {
            get {
                return ResourceManager.GetString("ReceptionDetailSectionLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logistic data.
        /// </summary>
        internal static string ReceptionDetailSectionLogistic {
            get {
                return ResourceManager.GetString("ReceptionDetailSectionLogistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sample data.
        /// </summary>
        internal static string ReceptionDetailSectionSample {
            get {
                return ResourceManager.GetString("ReceptionDetailSectionSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detail.
        /// </summary>
        internal static string ReceptionDetailTitle {
            get {
                return ResourceManager.GetString("ReceptionDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight.
        /// </summary>
        internal static string ReceptionDetailWeight {
            get {
                return ResourceManager.GetString("ReceptionDetailWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Width.
        /// </summary>
        internal static string ReceptionDetailWidth {
            get {
                return ResourceManager.GetString("ReceptionDetailWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Article not found in master data. Please check the code..
        /// </summary>
        internal static string ReceptionErrorArticleInvalid {
            get {
                return ResourceManager.GetString("ReceptionErrorArticleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Article is required..
        /// </summary>
        internal static string ReceptionErrorArticleRequired {
            get {
                return ResourceManager.GetString("ReceptionErrorArticleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please complete all checklist items before continuing..
        /// </summary>
        internal static string ReceptionErrorChecklistIncomplete {
            get {
                return ResourceManager.GetString("ReceptionErrorChecklistIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter or scan a reception number..
        /// </summary>
        internal static string ReceptionErrorEmptyNumber {
            get {
                return ResourceManager.GetString("ReceptionErrorEmptyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location not found. Please check the code..
        /// </summary>
        internal static string ReceptionErrorLocationInvalid {
            get {
                return ResourceManager.GetString("ReceptionErrorLocationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location is required..
        /// </summary>
        internal static string ReceptionErrorLocationRequired {
            get {
                return ResourceManager.GetString("ReceptionErrorLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No active reception session. Please start a new reception..
        /// </summary>
        internal static string ReceptionErrorNoActiveSession {
            get {
                return ResourceManager.GetString("ReceptionErrorNoActiveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a At least one detail line is required..
        /// </summary>
        internal static string ReceptionErrorNoDetails {
            get {
                return ResourceManager.GetString("ReceptionErrorNoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reception not found. Please check the number and try again..
        /// </summary>
        internal static string ReceptionErrorNotFound {
            get {
                return ResourceManager.GetString("ReceptionErrorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity must be greater than 0..
        /// </summary>
        internal static string ReceptionErrorQuantityZero {
            get {
                return ResourceManager.GetString("ReceptionErrorQuantityZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recipient is required..
        /// </summary>
        internal static string ReceptionErrorRecipientRequired {
            get {
                return ResourceManager.GetString("ReceptionErrorRecipientRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a rejection reason..
        /// </summary>
        internal static string ReceptionErrorRejectionReasonRequired {
            get {
                return ResourceManager.GetString("ReceptionErrorRejectionReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sample reference is required for TEST SAMPLE flow..
        /// </summary>
        internal static string ReceptionErrorSampleReferenceRequired {
            get {
                return ResourceManager.GetString("ReceptionErrorSampleReferenceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sender is required..
        /// </summary>
        internal static string ReceptionErrorSenderRequired {
            get {
                return ResourceManager.GetString("ReceptionErrorSenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        internal static string ReceptionHeaderContinue {
            get {
                return ResourceManager.GetString("ReceptionHeaderContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delivery note.
        /// </summary>
        internal static string ReceptionHeaderDeliveryNote {
            get {
                return ResourceManager.GetString("ReceptionHeaderDeliveryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expected date.
        /// </summary>
        internal static string ReceptionHeaderExpectedDate {
            get {
                return ResourceManager.GetString("ReceptionHeaderExpectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flow type.
        /// </summary>
        internal static string ReceptionHeaderFlowType {
            get {
                return ResourceManager.GetString("ReceptionHeaderFlowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reception number.
        /// </summary>
        internal static string ReceptionHeaderNumber {
            get {
                return ResourceManager.GetString("ReceptionHeaderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observations.
        /// </summary>
        internal static string ReceptionHeaderObservations {
            get {
                return ResourceManager.GetString("ReceptionHeaderObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recipient.
        /// </summary>
        internal static string ReceptionHeaderRecipient {
            get {
                return ResourceManager.GetString("ReceptionHeaderRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reception info.
        /// </summary>
        internal static string ReceptionHeaderSectionInfo {
            get {
                return ResourceManager.GetString("ReceptionHeaderSectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observations.
        /// </summary>
        internal static string ReceptionHeaderSectionObservations {
            get {
                return ResourceManager.GetString("ReceptionHeaderSectionObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sender / Recipient.
        /// </summary>
        internal static string ReceptionHeaderSectionParties {
            get {
                return ResourceManager.GetString("ReceptionHeaderSectionParties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sender.
        /// </summary>
        internal static string ReceptionHeaderSender {
            get {
                return ResourceManager.GetString("ReceptionHeaderSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General data.
        /// </summary>
        internal static string ReceptionHeaderTitle {
            get {
                return ResourceManager.GetString("ReceptionHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish.
        /// </summary>
        internal static string ReceptionItemsFinish {
            get {
                return ResourceManager.GetString("ReceptionItemsFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generated items.
        /// </summary>
        internal static string ReceptionItemsSectionList {
            get {
                return ResourceManager.GetString("ReceptionItemsSectionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reception completed.
        /// </summary>
        internal static string ReceptionItemsSectionSummary {
            get {
                return ResourceManager.GetString("ReceptionItemsSectionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generated items.
        /// </summary>
        internal static string ReceptionItemsTitle {
            get {
                return ResourceManager.GetString("ReceptionItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total items.
        /// </summary>
        internal static string ReceptionItemsTotalItems {
            get {
                return ResourceManager.GetString("ReceptionItemsTotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total quantity.
        /// </summary>
        internal static string ReceptionItemsTotalQuantity {
            get {
                return ResourceManager.GetString("ReceptionItemsTotalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        internal static string ReceptionStartContinue {
            get {
                return ResourceManager.GetString("ReceptionStartContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reception number.
        /// </summary>
        internal static string ReceptionStartNumberLabel {
            get {
                return ResourceManager.GetString("ReceptionStartNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scan or enter reception number.
        /// </summary>
        internal static string ReceptionStartNumberPlaceholder {
            get {
                return ResourceManager.GetString("ReceptionStartNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load reception.
        /// </summary>
        internal static string ReceptionStartScanButton {
            get {
                return ResourceManager.GetString("ReceptionStartScanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reception.
        /// </summary>
        internal static string ReceptionStartTitle {
            get {
                return ResourceManager.GetString("ReceptionStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a External.
        /// </summary>
        internal static string ScannerExternal {
            get {
                return ResourceManager.GetString("ScannerExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internal.
        /// </summary>
        internal static string ScannerInternal {
            get {
                return ResourceManager.GetString("ScannerInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active user.
        /// </summary>
        internal static string SettingsActiveUser {
            get {
                return ResourceManager.GetString("SettingsActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Demo mode.
        /// </summary>
        internal static string SettingsDemoMode {
            get {
                return ResourceManager.GetString("SettingsDemoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Environment.
        /// </summary>
        internal static string SettingsEnvironment {
            get {
                return ResourceManager.GetString("SettingsEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error sound.
        /// </summary>
        internal static string SettingsErrorSound {
            get {
                return ResourceManager.GetString("SettingsErrorSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        internal static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore defaults.
        /// </summary>
        internal static string SettingsRestoreDefaults {
            get {
                return ResourceManager.GetString("SettingsRestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scanner type.
        /// </summary>
        internal static string SettingsScannerType {
            get {
                return ResourceManager.GetString("SettingsScannerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string SettingsSectionAbout {
            get {
                return ResourceManager.GetString("SettingsSectionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        internal static string SettingsSectionGeneral {
            get {
                return ResourceManager.GetString("SettingsSectionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scanner.
        /// </summary>
        internal static string SettingsSectionScanner {
            get {
                return ResourceManager.GetString("SettingsSectionScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server / Environment.
        /// </summary>
        internal static string SettingsSectionServer {
            get {
                return ResourceManager.GetString("SettingsSectionServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server URL.
        /// </summary>
        internal static string SettingsServerUrl {
            get {
                return ResourceManager.GetString("SettingsServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success sound.
        /// </summary>
        internal static string SettingsSuccessSound {
            get {
                return ResourceManager.GetString("SettingsSuccessSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success vibration.
        /// </summary>
        internal static string SettingsSuccessVibration {
            get {
                return ResourceManager.GetString("SettingsSuccessVibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test connection.
        /// </summary>
        internal static string SettingsTestConnection {
            get {
                return ResourceManager.GetString("SettingsTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test scanner.
        /// </summary>
        internal static string SettingsTestScanner {
            get {
                return ResourceManager.GetString("SettingsTestScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visual theme.
        /// </summary>
        internal static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timeout (sec).
        /// </summary>
        internal static string SettingsTimeout {
            get {
                return ResourceManager.GetString("SettingsTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string SettingsUser {
            get {
                return ResourceManager.GetString("SettingsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        internal static string SettingsVersion {
            get {
                return ResourceManager.GetString("SettingsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dark.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Light.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
    }
}
