namespace LogiFlow.Mobile.DTOs;

/// <summary>
/// Represents a logistic item generated after a reception is confirmed.
/// </summary>
public class ItemDto
{
    /// <summary>Gets or sets the unique item code generated by the system.</summary>
    public string ItemCode { get; set; } = string.Empty;

    /// <summary>Gets or sets the article code associated to this item.</summary>
    public string Article { get; set; } = string.Empty;

    /// <summary>Gets or sets the article description.</summary>
    public string ArticleDescription { get; set; } = string.Empty;

    /// <summary>Gets or sets the quantity of units in this item.</summary>
    public int Quantity { get; set; }

    /// <summary>Gets or sets the warehouse location assigned to this item.</summary>
    public string Location { get; set; } = string.Empty;

    /// <summary>Gets or sets the item status after generation.</summary>
    public string Status { get; set; } = string.Empty;
}
